---
- name: ensure rabbitmq packages are installed
  apt: 
    pkg: "{{ item }}"
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - rabbitmq-server

- name: ensure supervisor is installed for dockerized deployments
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - supervisor
  when: rabbitmq_dockerize_context is defined

- name: update supervisor configuration from template for dockerized deployments
  template:
    src: etc/supervisor/conf.d/supervisord.conf
    dest: /etc/supervisor/conf.d/supervisord.conf
    owner: root
    group: root
    mode: 0644
  when: rabbitmq_dockerize_context is defined

- name: ensure rabbitmq is started and enabled
  service: 
    name: rabbitmq-server
    state: started 
    enabled: yes

- name: ensure anonymous guest user is absent
  rabbitmq_user:
    user: guest
    state: absent

- name: ensure rabbitmq is properly shut down for docker
  service: 
    name: rabbitmq-server
    state: stopped
  when: rabbitmq_dockerize_context is defined
